name: angular_todo
version: 0.1.0
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  bridge: ^1.0.0-beta.1
  todo_service:
    path: ../todo_service
  angular2: ^2.0.0-alpha.45
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^0.1.0+4
dev_dependencies:
  test: any
  grinder: any
transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
